name: pphotoeditor
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  colorfilter_generator: ^0.0.8
  image: ^4.1.6
  path_provider: ^2.0.4
  image_crop_plus: ^1.0.0
  flutter_svg: ^2.0.9
  share_plus: ^10.1.4
  image_gallery_saver_plus: ^3.0.5
  flutter_widget_from_html: ^0.15.3
  url_launcher: ^6.3.0
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/articles/
    - assets/images/
    - assets/images/editor/
  fonts:
    - family: Pompiere
      fonts:
        - asset: assets/fonts/Pompiere-Regular.ttf

    - family: Karantina
      fonts:
        - asset: assets/fonts/Karantina-Regular.ttf
